# Dockerfile
ARG PYTHON_VERSION=3.10
FROM python:${PYTHON_VERSION}-slim

ENV PYTHONUNBUFFERED 1
ENV PYTHONDONTWRITEBYTECODE 1

RUN apt-get update && \
    apt-get install -y --no-install-recommends \
    build-essential \
    libaio1 \
    libxml2-dev \
    libxslt1-dev \
    gcc \
    libpq-dev && \
    rm -rf /var/lib/apt/lists/*

WORKDIR /code

COPY requirements.txt /tmp/requirements.txt
RUN pip install --upgrade pip
RUN pip install -r /tmp/requirements.txt

COPY wallet /app/wallet/
RUN chmod -R 777 /app/wallet/

COPY . /code/

CMD ["gunicorn", "--bind", "0.0.0.0:8080", "--workers", "2", "backend.wsgi:application"]