# fly.toml
app = 'ararat-web-backend'
primary_region = 'fra' # İsteğe bağlı olarak 'ist' yapabilirsiniz.
console_command = '/code/manage.py shell'

[build]
  builder = "paketobuildpacks/builder:base"
  

[deploy]
  release_command = 'python manage.py migrate --noinput'

[env]
  PORT = '8080'
  TNS_ADMIN = '/app/wallet'  # <-- BU AYARI EKLEYİN VEYA GÜNCELLEYİN

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 1 # İlk yükleme hızını artırmak için 1 yapıldı
  processes = ['app']

[[vm]]
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 512 # Daha düşük hafıza ile deneme için 512MB yapıldı

[[statics]]
  guest_path = '/code/staticfiles' # settings.py'deki STATIC_ROOT ile eşleşmesi için düzeltildi
  url_prefix = '/static/'