# Generated by Django 6.0 on 2025-12-14 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactPageContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_title_tr', models.CharField(max_length=100, verbose_name='Sayfa Basligi (TR)')),
                ('page_title_en', models.CharField(max_length=100, verbose_name='Sayfa Basligi (EN)')),
                ('warning_text_tr', models.TextField(verbose_name='Yasal Uyari Metni (TR)')),
                ('warning_text_en', models.TextField(verbose_name='Yasal Uyari Metni (EN)')),
                ('whatsapp_number', models.CharField(help_text='WhatsApp telefon numarasi', max_length=20)),
            ],
            options={
                'verbose_name': 'Iletisim Sayfasi Icerigi',
                'verbose_name_plural': 'Iletisim Sayfasi Icerigi',
            },
        ),
        migrations.CreateModel(
            name='FeatureCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(unique=True, verbose_name='Sirasi')),
                ('icon_name', models.CharField(help_text='Lucide ikon adi (Orn: shield, search)', max_length=50)),
                ('title_tr', models.CharField(max_length=100, verbose_name='Baslik (TR)')),
                ('title_en', models.CharField(max_length=100, verbose_name='Baslik (EN)')),
                ('description_tr', models.TextField(verbose_name='Aciklama (TR)')),
                ('description_en', models.TextField(verbose_name='Aciklama (EN)')),
            ],
            options={
                'verbose_name': 'Ozellik Karti',
                'verbose_name_plural': 'Ozellik Kartlari',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='HomePageContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slogan_tr', models.CharField(max_length=255, verbose_name='Slogan (TR)')),
                ('slogan_en', models.CharField(max_length=255, verbose_name='Slogan (EN)')),
                ('subheadline_tr', models.TextField(verbose_name='Alt Baslik (TR)')),
                ('subheadline_en', models.TextField(verbose_name='Alt Baslik (EN)')),
            ],
            options={
                'verbose_name': 'Ana Sayfa Icerigi',
                'verbose_name_plural': 'Ana Sayfa Icerigi',
            },
        ),
        migrations.CreateModel(
            name='PurposePageContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('main_text_tr', models.TextField(verbose_name='Ana Açıklama Paragrafı (TR)')),
                ('main_text_en', models.TextField(verbose_name='Ana Açıklama Paragrafı (EN)')),
                ('main_image', models.ImageField(upload_to='content_images/purpose/', verbose_name='Sayfa Ana Resmi')),
            ],
            options={
                'verbose_name': 'Amacimiz Sayfa Icerigi',
                'verbose_name_plural': 'Amacimiz Sayfa Icerigi',
            },
        ),
        migrations.CreateModel(
            name='TimelineCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(unique=True, verbose_name='Sıra Numarası')),
                ('title_tr', models.CharField(max_length=100, verbose_name='Kart Başlığı (TR)')),
                ('title_en', models.CharField(max_length=100, verbose_name='Kart Başlığı (EN)')),
                ('description_tr', models.TextField(verbose_name='Açıklama Metni (TR)')),
                ('description_en', models.TextField(verbose_name='Açıklama Metni (EN)')),
            ],
            options={
                'verbose_name': 'Zaman Çizelgesi Kartı',
                'verbose_name_plural': 'Zaman Çizelgesi Kartları',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='WhatIsAraratTokenContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_tr', models.CharField(max_length=150, verbose_name='Başlık (TR)')),
                ('title_en', models.CharField(max_length=150, verbose_name='Başlık (EN)')),
                ('text_tr', models.TextField(verbose_name='Paragraf Metni (TR)')),
                ('text_en', models.TextField(verbose_name='Paragraf Metni (EN)')),
                ('main_image', models.ImageField(upload_to='content_images/what_is_token/', verbose_name='Sayfa Resmi')),
            ],
            options={
                'verbose_name': 'Ararat Token Nedir Icerigi',
                'verbose_name_plural': 'Ararat Token Nedir Icerigi',
            },
        ),
        migrations.CreateModel(
            name='WhyAraratNameContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_tr', models.CharField(max_length=150, verbose_name='Başlık (TR)')),
                ('title_en', models.CharField(max_length=150, verbose_name='Başlık (EN)')),
                ('text_tr', models.TextField(verbose_name='Paragraf Metni (TR)')),
                ('text_en', models.TextField(verbose_name='Paragraf Metni (EN)')),
                ('main_image', models.ImageField(upload_to='content_images/why_ararat/', verbose_name='Sayfa Resmi')),
            ],
            options={
                'verbose_name': 'Neden Ararat İsmi Icerigi',
                'verbose_name_plural': 'Neden Ararat İsmi Icerigi',
            },
        ),
    ]
